# Build dedicated server
BUILD_SERVER = 1

# Build client
BUILD_CLIENT = 1

# Add OpenAL support
USE_OPENAL = 1
USE_OPENAL_DLOPEN = 0

# Add Vorbis support
USE_CODEC_VORBIS = 0

# Build game logic as native DLL
BUILD_GAME_SO = 1

# Build game logic as VM
BUILD_GAME_QVM = 0

# Build missionpack stuff
BUILD_MISSIONPACK = 0

# Use VOIP
USE_VOIP = 0

# Make a stand-alone game
BUILD_STANDALONE = 0

# Make private OpenGL rendering library
USE_RENDERER_DLOPEN=0

# Game install directory
COPYDIR=e:/quake3

# Use anti-cheat code
USE_ANTICHEAT = 1

# Create a PAK archive containing the VM modules
BUILD_PAK = 0
PAK_NUM = 8

# Use extra debug functions
USE_XDEBUG = 1
